### ISSUE TITLE
PID_D[yaw] is missing in the log file

### ISSUE THREAD

**Issue by Airwide** [cleanflight/blackbox-firmware#5]
PID_D[yaw](axisD[2]) is missing in the log file. I guess it has to do with different implementation of yaw in different pid controllers, but wouldn't it be possible to include it in the logs anyway?

**Comment by thenickdude** [comment]
It's intentionally not recorded when you've set your yaw D term to zero, since this makes the D value always zero and there's no point in recording it.

Note that there is a bug with the Blackbox for PID controller 1 where it would fail to record yaw D even if your yaw D setting was non-zero. This should be fixed in the 1.9.0 RC. In 1.8.1 you can work around it by switching to one of the other PID controllers, setting their D term to a non-zero value, then switching back to PID controller 1.
